version: '3.3'
services:
  gateway:
    build: ./gateway
    image: beinan/gateway:devel
    ports:
     - "8888"
    links:
     - user-service
    volumes:
     - ./gateway:/go/src/github.com/beinan/gql-server-examples/gateway
  user-service:
    build: ./user-service
    image: beinan/user-service:devel
    ports:
     - "9090"
    volumes:
     - ./user-service:/go/src/github.com/beinan/gql-server-examples/user-service
  lb:
    image: 'dockercloud/haproxy:latest'
    links:
     - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
     - '8888:80'
